name: "Qlty Install"
description: "Install the Qlty CLI"
author: "Qlty"

branding:
  icon: "package"
  color: "green"

inputs:
  github-token:
    description: "GitHub token for sigstore attestation verification"
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
