// Re-export from shared installer package
export {
  Installer,
  type InstallerOptions,
  type NullInstallerOptions,
  GhAttestationVerifier,
  type AttestationResult,
  type AttestationVerifier,
  planDownload,
  type DownloadPlan,
  type FileType,
  type ToolCache,
  type OperatingSystem,
  type ActionOutput,
  StubbedAttestationVerifier,
  StubbedOperatingSystem,
  StubbedToolCache,
  StubbedOutput,
  type AttestationBehavior,
  OutputTracker,
} from "@qltysh-action/shared";
